version: "2"

volumes:
  db:
    driver: local

services:
  web:
    build: .
    volumes:
      - ".:/app"
    environment:
      DATABASE_URL: postgres://web:secretpassword@db:5432/web
      CACHE_URL: redis://redis:6379
      SECRET_KEY: notsosecret
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
  db:
    image: postgres:9.4
    volumes:
      - "db:/var/lib/postgres/data"
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: secretpassword
  redis:
    image: redis
